# Generated by Django 4.2.7 on 2023-11-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_date', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('catalog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_app.catalog')),
            ],
        ),
    ]
