# Generated by Django 4.2.7 on 2023-11-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_catalog_title_alter_catalog_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='catalog',
        ),
        migrations.AddField(
            model_name='catalog',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_app.book'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
