# Generated by Django 4.2.7 on 2023-11-05 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_book_catalog_catalog_book_alter_catalog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.book'),
        ),
    ]
