# Generated by Django 4.2.7 on 2023-11-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_catalog_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='book_app.book'),
        ),
    ]
