# Generated by Django 4.2.7 on 2023-11-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_remove_catalog_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.book'),
        ),
    ]
