# Generated by Django 4.2.7 on 2023-11-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_remove_catalog_book_book_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Catalog',
            new_name='catalog',
        ),
    ]
