# Generated by Django 4.2.7 on 2023-11-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_rename_catalog_book_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.catalog')),
            ],
        ),
    ]
