# Generated by Django 4.2.7 on 2023-11-17 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_app', '0012_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='catalog',
        ),
        migrations.AddField(
            model_name='catalog',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to=settings.AUTH_USER_MODEL),
        ),
    ]
