# Generated by Django 4.2.7 on 2023-11-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_remove_member_catalog_catalog_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='book_app.catalog'),
        ),
    ]
