# Generated by Django 4.2.7 on 2023-11-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_alter_catalog_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='book_app.catalog'),
        ),
    ]
