# Generated by Django 4.2.7 on 2023-11-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0018_alter_member_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='catalog',
        ),
    ]
