# Generated by Django 4.2.7 on 2023-11-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0022_alter_member_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='catalog',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='book_app.member'),
        ),
    ]
