# Generated by Django 4.2.7 on 2023-11-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_app', '0023_remove_member_catalog_alter_catalog_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='book_app.catalog'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
