# Generated by Django 4.2.7 on 2023-11-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0024_member_catalog_alter_catalog_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='catalog',
        ),
    ]
